name: Deploy to Amazon Linux

on:
  push:
    branches:
      - master

permissions:
  id-token: write # This is required for the JWT
  contents: read  # This is required for the actions/checkout
  security-events: write
  actions: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy WAR File to Server
        uses: appleboy/scp-action@master
        with:
          host: "18.225.36.196"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/user-api-consumer-0.0.1-SNAPSHOT.war"
          target: "/var/lib/tomcat/webapps/user-api-consumer-0.0.1-SNAPSHOT.war"

      - name: SSH into Server and Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: "18.225.36.196"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart tomcat

      - name: Wait for Tomcat to Restart
        run: sleep 30

      - name: Verify Tomcat Status
        uses: appleboy/ssh-action@master
        with:
          host: "18.225.36.196"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl status tomcat
