name: Deploy to Amazon Linux

on:
  push:
    branches:
      - master

permissions:
  id-token: write # This is required for the JWT
  contents: read  # This is required for the actions/checkout
  security-events: write
  actions: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install SSH key
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known-hosts: |
      #       18.220.191.26 ssh-rsa sU4/z0n3PNMI+PQLl0WMOlIVvKZnPupFRs4k1aieVwo

      # - name: Deploy to Amazon Linux
      #   run: |
      #     scp -r ./target/* ec2-user@18.220.191.26:/var/lib/tomcat/webapps
      #     ssh ec2-user@18.220.191.26 'sudo systemctl restart tomcat.service'

      - name: Copy WAR File to Server
        uses: appleboy/scp-action@master
        with:
          host: "18.216.132.101"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*"
          target: "/etc/tomcat/"

      - name: SSH into Server and Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: "18.216.132.101"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart tomcat

      - name: Wait for Tomcat to Restart
        run: sleep 30

      - name: Verify Tomcat Status
        uses: appleboy/ssh-action@master
        with:
          host: "18.216.132.101"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl status tomcat
